# Generated by Django 4.2 on 2023-03-15 16:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("numero", models.TextField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True, max_length=100)),
                (
                    "docRecepiss",
                    models.FileField(
                        blank=True, null=True, upload_to="VerifyDocument/"
                    ),
                ),
                (
                    "activitePrincipal",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="distribution", max_length=100
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "activiteSecondaire",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="sante", max_length=100
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "activiteThird",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="assistance", max_length=100
                        ),
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
