# Generated by Django 4.2 on 2023-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="numero",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
